### ISSUE TITLE
Getting cannot reshape array when running

### ISSUE THREAD

**Issue by alexsaleh** [Sarthakdtu/Road-Cracks-Detection-Neural-Network-#1]
Hey there,

I really like what you've done here and would love to try it out on some images I have. I'm trying to run your code on your data set and I'm getting the following error during training:

`Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1758, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Crack Detection.py", line 124, in <module>
    final_train_colr = np.array(train_data_colr).reshape(((len(train_data_colr), 227, 227, 1)))
ValueError: cannot reshape array of size 3000 into shape (3000,227,227,1)`

Seems like there is an issue with image sizes. 
do you know why? 
thanks!

**Comment by troylane** [comment]
Hello,

I am having the same issue as alexsaleh 

Was there ever a resolution to this issue?  If so what did you do?

Thanks in advance.

**Comment by Sarthakdtu** [comment]
@alexsaleh  @troylane 
Hey, thanks for pointing out the issue. I think you have to reshape the images to 227 X 227 X 1.
Please let me know if you were able to do that. I think that part of the code is missing here.

**Comment by Sarthakdtu** [comment]
Hi, for anyone who stumbles upon this issue ever:-
Remember to put your images in right directory.
Crack images are in ```data/positive/``` and Non-Crack images are in ```data/negative```.
