### ISSUE TITLE
Data set failure

### ISSUE THREAD

**Issue by leader402** [Sarthakdtu/Road-Cracks-Detection-Neural-Network-#2]
The data set link is invalid, can you share the data set again? Thank you

**Comment by Sarthakdtu** [comment]
Hi @leader402 ,
Thanks for pointing this out. I just saw that the page is missing. I will try to find out some more links for dataset. Meanwhile, feel free to suggest some other dataset.

**Comment by abc1044** [comment]
Try this address：https://md-datasets-cache-zipfiles-prod.s3.eu-west-1.amazonaws.com/5y9wdsg2zt-1.zip

**Comment by Sarthakdtu** [comment]
@leader402 
Fixed by @abc1044 . Please check

**Comment by leader402** [comment]
Thank&nbsp;you&nbsp;very&nbsp;much&nbsp;for&nbsp;your data.Sorry for the late reply .




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sarthak Srivastava"<notifications@github.com&gt;; 
发送时间: 2021年1月7日(星期四) 晚上11:01
收件人: "Sarthakdtu/Road-Cracks-Detection-Neural-Network-"<Road-Cracks-Detection-Neural-Network-@noreply.github.com&gt;; 
抄送: "张政谦"<1103337036@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Sarthakdtu/Road-Cracks-Detection-Neural-Network-] Data set failure (#2)





 
@leader402
 Fixed by @abc1044 . Please check

**Comment by leader402** [comment]
> Try this address：https://md-datasets-cache-zipfiles-prod.s3.eu-west-1.amazonaws.com/5y9wdsg2zt-1.zip

thank you very much . i download sucessfully!
