### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by furqan5411** [Sarthakdtu/Road-Cracks-Detection-Neural-Network-#3]
Link is not working unable to get the data set

**Comment by Sarthakdtu** [comment]
Hi @furqan5411  
Thanks for pointing this out. I just saw that the page is missing. I will try to find out some more links for the dataset. Meanwhile, feel free to suggest some other dataset.

**Comment by amitdaskr** [comment]
Hi @Sarthakdtu,

Can you please share the dataset

**Comment by abc1044** [comment]
Just delete the last character of the link in the project, try this address：https://data.mendeley.com/datasets/5y9wdsg2zt/1

**Comment by Sarthakdtu** [comment]
@abc1044 Thanks for pointing this out. I will update this is in the README.
